### PR TITLE
Include URL hash in build.log

### PR DESCRIPTION
**Pull request by sigmundch**
URL was included in platform.js, but was missing in the build.log file

### CODE REVIEW

**Comment by jakemac53** [comment]
looks like ../WeakMap should be added too

**Comment by jmesserly** [comment]
crazy idea: compute this using the data returned by `readManifest` ?

**Comment by jakemac53** [comment]
nah, that makes to much sense :)

**Comment by sigmundch** [comment]
Added weakmap, but also created #48 following @jmesserly's suggestion. Your pick :-)

**Comment by jmesserly** [comment]
closing this since it was superseded by #48 :)

**Pull request closed without merging**
