### PR TITLE
Fixes issue #22 (Internet Explorer: Member not found in ShadowCSS.js)

### PR DESCRIPTION
**Pull request by ghost**
Fixes https://github.com/Polymer/platform-dev/issues/22

### CODE REVIEW

**Comment by ebidel** [comment]
Before this PR can be merged, please sign the CLA. See the [CONTRIBUTING](http://polymer.github.io/CONTRIBUTORS.txt) guide.

**Comment by addyosmani** [comment]
@DominikMayrhofer are you still interested in chasing this up? If so, could you sign the CLA and rebase?

**Comment by ghost** [comment]
Nope, sorry i will not sign Googles CLA.

**Comment by sorvell** [comment]
Already fixed by https://github.com/Polymer/platform-dev/commit/712c68dd1ecba8d7b3fbe90870c8782b41e3b3ab

**Pull request closed without merging**
