### PR TITLE
Make boot-time shadow dom warning a log instead

### PR DESCRIPTION
**Pull request by jerub**
Change console.warn() on boot when platform.js is not first script on page to console.log() - some javascript testing frameworks insert javascript at the start of the html to assist with accurate testing, and will fail tests if they see console.warn().

### CODE REVIEW

**Comment by ebidel** [comment]
Before this PR can be merged, please sign the CLA. See the [CONTRIBUTING](http://polymer.github.io/CONTRIBUTORS.txt) guide.

**Comment by jerub** [comment]
I have submitted this pull request: https://github.com/Polymer/polymer.github.io/pull/19 to add my name to CONTRIBUTORS.txt, and I have been added to the google group on github:  https://github.com/orgs/google/people?query=jerub

**Comment by ebidel** [comment]
Ah, you're a Googler. No need for the CLA then. I'll whitelist you.

**Comment by ebidel** [comment]
Thanks for signing the CLA!

**Comment by jmesserly** [comment]
> some javascript testing frameworks insert javascript at the start of the html to assist with accurate testing, and will fail tests if they see console.warn().

what frameworks?

It worries me to downgrade this to just a log message. If platform.js is not first, some code is going to see a different view of the DOM compared to other code, potentially leading to subtle bugs. That's why the warning was added.

**Comment by jmesserly** [comment]
Another thought here, maybe we could make the message stand out by adding a "Warning: " prefix to it?
console.log('Warning: platform.js is not the first script on the page. ')

at least that calls folks attention to it...

**Comment by arv** [comment]
@jmesserly I like that. @jerub Care to add a `Warning:` prefix?

**Comment by jerub** [comment]
I have added the "Warning: " prefix.

**Comment by jmesserly** [comment]
Nice, thank you!

**Pull request merged**
