### PR TITLE
Add a console warning if platform.js is not the first script

### PR DESCRIPTION
**Pull request by arv**

### CODE REVIEW

**Comment by arv** [comment]
Is this the best place to put this test?

**Comment by sjmiles** [comment]
This seems like a logical place to me, thanks for doing that. 

Probably want to have a bit more information in the warning, will ask around.

Lastly, the whole `if-poly` stuff is grotesque, but that's a separate can'o'worms.

**Comment by arv** [comment]
Maybe we should put a link in there that points to some page on polymer-project.org?

@ebidel

**Comment by ebidel** [comment]
Probably http://www.polymer-project.org/docs/start/platform.html#setup

**Comment by arv** [comment]
PTAL

**Comment by arv** [comment]
Ping

**Comment by dfreedm** [comment]
LGTM

**Pull request merged**
